name: rp2 port

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'micropython repo'  # test build with space in path
    steps:
    - uses: actions/checkout@v4
      with:
        path: 'micropython repo'
    - name: Install packages
      run: source tools/ci.sh && ci_rp2_setup
    - name: Build
      run: source tools/ci.sh && ci_rp2_build
